# Generated by Django 4.2.8 on 2024-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_new_user_customuser_new_user_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_user_link_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
