# Generated by Django 4.2.8 on 2024-01-17 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_avatar_customuser_new_user_link_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='books',
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A lire', 'To Read'), ('En cours', 'Reading'), ('Lu', 'Read'), ('Abandonné', 'Abandoned')], default='A lire', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
