# Generated by Django 4.2.8 on 2024-01-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='userbook',
        ),
        migrations.AddField(
            model_name='news',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
        ),
    ]
