# Generated by Django 4.2.8 on 2024-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nb_added_friends',
            field=models.IntegerField(default=0),
        ),
    ]
