# Generated by Django 4.2.8 on 2024-01-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_nb_added_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_user_link_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
