# Generated by Django 4.2.8 on 2024-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('En attente', 'Pending'), ('Accepté', 'Accepted'), ('Invité', 'Invited')], default='En attente', max_length=10),
        ),
    ]
